const prisma = require("../../utils/prisma");
const PDFDocument = require("pdfkit");

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = Object.keys(rows[0]);
  const lines = [headers.join(",")];
  for (const row of rows) {
    const values = headers.map((h) => {
      const value = row[h] == null ? "" : String(row[h]).replaceAll('"', '""');
      return `"${value}"`;
    });
    lines.push(values.join(","));
  }
  return lines.join("\n");
}

function writePdfTableReport(res, title, columns, rows) {
  const doc = new PDFDocument({ margin: 40, size: "A4", bufferPages: true });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${title.toLowerCase().replaceAll(" ", "-")}.pdf"`);
  doc.pipe(res);

  const storeName = process.env.REPORT_STORE_NAME || "BD Smart POS";
  const storeAddress = process.env.REPORT_STORE_ADDRESS || "Dhaka, Bangladesh";
  const storePhone = process.env.REPORT_STORE_PHONE || "";
  const footerText = process.env.REPORT_FOOTER_TEXT || "Generated by BD Smart POS";
  const generatedAt = new Date().toLocaleString("bn-BD");

  doc.fontSize(16).font("Helvetica-Bold").text(storeName, { align: "center" });
  doc.moveDown(0.1);
  doc.fontSize(10).font("Helvetica").text(storeAddress, { align: "center" });
  if (storePhone) {
    doc.text(`Phone: ${storePhone}`, { align: "center" });
  }
  doc.moveDown(0.3);
  doc.fontSize(14).font("Helvetica-Bold").text(title, { align: "center" });
  doc.fontSize(10).font("Helvetica").text(`Generated: ${generatedAt}`, { align: "center" });
  doc.moveDown(1);

  const startX = 40;
  let y = doc.y;
  const tableWidth = 515;
  const colWidth = tableWidth / columns.length;

  doc.fontSize(10).font("Helvetica-Bold");
  columns.forEach((col, idx) => {
    doc.text(col.label, startX + idx * colWidth, y, { width: colWidth, align: "left" });
  });
  y += 18;
  doc.moveTo(startX, y - 4).lineTo(startX + tableWidth, y - 4).stroke("#888");

  doc.font("Helvetica");
  rows.forEach((row) => {
    if (y > 760) {
      doc.addPage();
      y = 50;
    }
    columns.forEach((col, idx) => {
      const value = row[col.key] == null ? "" : String(row[col.key]);
      doc.text(value, startX + idx * colWidth, y, { width: colWidth, align: "left" });
    });
    y += 18;
  });

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(9).fillColor("#666");
    doc.text(
      `${footerText} | Page ${i + 1} of ${range.count}`,
      40,
      810,
      { align: "center", width: 515 }
    );
  }

  doc.end();
}

exports.getDashboard = async (req, res) => {
  try {
    const branchId = req.branchId;
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const sales = await prisma.sale.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const purchases = await prisma.purchase.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const products = await prisma.product.findMany({ where: { branchId } });
    const stockAlerts = products.filter((p) => p.stock <= p.reorderLevel).length;
    const totals = {
      sales: sales.reduce((a, x) => a + x.total, 0),
      collections: sales.reduce((a, x) => a + x.paidAmount, 0),
      purchase: purchases.reduce((a, x) => a + x.total, 0),
      stockAlerts,
    };
    res.json(totals);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getAging = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    res.json({ customers, suppliers });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getStockValuation = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      productId: p.id,
      name: p.name,
      stock: p.stock,
      unitCost: p.price,
      valuation: Number(p.stock) * Number(p.price),
    }));
    const totalValue = rows.reduce((sum, r) => sum + r.valuation, 0);
    res.json({ totalValue, rows });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      product_id: p.id,
      product_name: p.name,
      stock: p.stock,
      unit_cost: p.price,
      valuation: Number(p.stock) * Number(p.price),
    }));
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="stock-valuation.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportAgingCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "CustomerDue",
        name: c.name,
        phone: c.phone || "",
        amount: c.balance,
      })),
      ...suppliers.map((s) => ({
        type: "SupplierPayable",
        name: s.name,
        phone: s.phone || "",
        amount: s.payableBalance,
      })),
    ];
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="aging-report.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      name: p.name,
      stock: p.stock,
      unitCost: Number(p.price).toFixed(2),
      valuation: (Number(p.stock) * Number(p.price)).toFixed(2),
    }));
    writePdfTableReport(
      res,
      "Stock Valuation Report",
      [
        { key: "name", label: "Product" },
        { key: "stock", label: "Stock" },
        { key: "unitCost", label: "Unit Cost" },
        { key: "valuation", label: "Valuation" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportAgingPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "Customer Due",
        name: c.name,
        phone: c.phone || "",
        amount: Number(c.balance).toFixed(2),
      })),
      ...suppliers.map((s) => ({
        type: "Supplier Payable",
        name: s.name,
        phone: s.phone || "",
        amount: Number(s.payableBalance).toFixed(2),
      })),
    ];
    writePdfTableReport(
      res,
      "Aging Report",
      [
        { key: "type", label: "Type" },
        { key: "name", label: "Name" },
        { key: "phone", label: "Phone" },
        { key: "amount", label: "Amount" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
