const prisma = require("../../utils/prisma");
const PDFDocument = require("pdfkit");

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = Object.keys(rows[0]);
  const lines = [headers.join(",")];
  for (const row of rows) {
    const values = headers.map((h) => {
      const value = row[h] == null ? "" : String(row[h]).replaceAll('"', '""');
      return `"${value}"`;
    });
    lines.push(values.join(","));
  }
  return lines.join("\n");
}

function writePdfTableReport(res, title, columns, rows) {
  const doc = new PDFDocument({ margin: 40, size: "A4", bufferPages: true });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${title.toLowerCase().replaceAll(" ", "-")}.pdf"`);
  doc.pipe(res);

  const storeName = process.env.REPORT_STORE_NAME || "BD Smart POS";
  const storeAddress = process.env.REPORT_STORE_ADDRESS || "Dhaka, Bangladesh";
  const storePhone = process.env.REPORT_STORE_PHONE || "";
  const footerText = process.env.REPORT_FOOTER_TEXT || "Generated by BD Smart POS";
  const generatedAt = new Date().toLocaleString("bn-BD");

  doc.fontSize(16).font("Helvetica-Bold").text(storeName, { align: "center" });
  doc.moveDown(0.1);
  doc.fontSize(10).font("Helvetica").text(storeAddress, { align: "center" });
  if (storePhone) {
    doc.text(`Phone: ${storePhone}`, { align: "center" });
  }
  doc.moveDown(0.3);
  doc.fontSize(14).font("Helvetica-Bold").text(title, { align: "center" });
  doc.fontSize(10).font("Helvetica").text(`Generated: ${generatedAt}`, { align: "center" });
  doc.moveDown(1);

  const startX = 40;
  let y = doc.y;
  const tableWidth = 515;
  const colWidth = tableWidth / columns.length;

  doc.fontSize(10).font("Helvetica-Bold");
  columns.forEach((col, idx) => {
    doc.text(col.label, startX + idx * colWidth, y, { width: colWidth, align: "left" });
  });
  y += 18;
  doc.moveTo(startX, y - 4).lineTo(startX + tableWidth, y - 4).stroke("#888");

  doc.font("Helvetica");
  rows.forEach((row) => {
    if (y > 760) {
      doc.addPage();
      y = 50;
    }
    columns.forEach((col, idx) => {
      const value = row[col.key] == null ? "" : String(row[col.key]);
      doc.text(value, startX + idx * colWidth, y, { width: colWidth, align: "left" });
    });
    y += 18;
  });

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(9).fillColor("#666");
    doc.text(
      `${footerText} | Page ${i + 1} of ${range.count}`,
      40,
      810,
      { align: "center", width: 515 }
    );
  }

  doc.end();
}

function parseDateRange(query = {}) {
  const from = query.from ? new Date(`${query.from}T00:00:00.000Z`) : null;
  const to = query.to ? new Date(`${query.to}T23:59:59.999Z`) : null;
  return { from, to };
}

function buildSaleWhere(branchId, from, to) {
  const where = { branchId };
  if (from || to) {
    where.createdAt = {};
    if (from) where.createdAt.gte = from;
    if (to) where.createdAt.lte = to;
  }
  return where;
}

async function getVatSalesRows(branchId, from, to) {
  const sales = await prisma.sale.findMany({
    where: buildSaleWhere(branchId, from, to),
    include: {
      customer: { select: { name: true, phone: true } },
    },
    orderBy: { createdAt: "asc" },
  });
  return sales.map((sale, idx) => {
    const total = Number(sale.total || 0);
    const vatAmount = Number(sale.vatAmount || 0);
    const taxableAmount = Math.max(0, total - vatAmount);
    return {
      serial: idx + 1,
      saleId: sale.id,
      invoiceNo: sale.invoiceNo || `INV-${sale.id}`,
      date: sale.createdAt.toISOString().slice(0, 10),
      customer: sale.customer?.name || "Walk-in",
      customerPhone: sale.customer?.phone || "-",
      taxableAmount: Number(taxableAmount.toFixed(2)),
      vatAmount: Number(vatAmount.toFixed(2)),
      grossAmount: Number(total.toFixed(2)),
    };
  });
}

async function getInputVatFromPurchases(branchId, from, to) {
  const purchases = await prisma.purchase.findMany({
    where: buildSaleWhere(branchId, from, to),
    include: {
      items: {
        include: {
          product: { select: { vatRate: true } },
        },
      },
    },
    orderBy: { createdAt: "asc" },
  });
  if (!purchases.length) {
    return { inputVat: 0, estimatedCount: 0, exactCount: 0 };
  }
  const purchaseIds = purchases.map((p) => p.id);
  const purchaseAuditLogs = await prisma.auditLog.findMany({
    where: {
      action: "PURCHASE_CREATE",
      entity: "Purchase",
      entityId: { in: purchaseIds },
    },
    select: { entityId: true, payload: true },
  });
  const inputVatByPurchaseId = new Map(
    purchaseAuditLogs
      .filter((x) => x.entityId != null)
      .map((x) => [Number(x.entityId), Number(x.payload?.inputVat || 0)])
  );

  let inputVat = 0;
  let estimatedCount = 0;
  let exactCount = 0;
  for (const purchase of purchases) {
    const purchaseId = Number(purchase.id);
    if (inputVatByPurchaseId.has(purchaseId)) {
      inputVat += Number(inputVatByPurchaseId.get(purchaseId) || 0);
      exactCount += 1;
      continue;
    }
    const estimated = (purchase.items || []).reduce((sum, item) => {
      const qty = Number(item.qty || 0);
      const cost = Number(item.cost || 0);
      const vatRate = Number(item.product?.vatRate || 0);
      if (vatRate <= 0) return sum;
      return sum + (qty * cost * vatRate) / 100;
    }, 0);
    inputVat += estimated;
    estimatedCount += 1;
  }
  return {
    inputVat: Number(inputVat.toFixed(2)),
    estimatedCount,
    exactCount,
  };
}

exports.getDashboard = async (req, res) => {
  try {
    const branchId = req.branchId;
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const sales = await prisma.sale.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const purchases = await prisma.purchase.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const products = await prisma.product.findMany({ where: { branchId } });
    const stockAlerts = products.filter((p) => p.stock <= p.reorderLevel).length;
    const totals = {
      sales: sales.reduce((a, x) => a + x.total, 0),
      collections: sales.reduce((a, x) => a + x.paidAmount, 0),
      purchase: purchases.reduce((a, x) => a + x.total, 0),
      stockAlerts,
    };
    res.json(totals);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getDashboardTrends = async (req, res) => {
  try {
    const branchId = req.branchId;
    const now = new Date();
    const startToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const startYesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);

    const [todaySalesRows, yesterdaySalesRows, todayPurchasesRows, yesterdayPurchasesRows, products, todayLedgers] =
      await Promise.all([
        prisma.sale.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { total: true, paidAmount: true },
        }),
        prisma.sale.findMany({
          where: { branchId, createdAt: { gte: startYesterday, lt: startToday } },
          select: { total: true, paidAmount: true },
        }),
        prisma.purchase.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { total: true },
        }),
        prisma.purchase.findMany({
          where: { branchId, createdAt: { gte: startYesterday, lt: startToday } },
          select: { total: true },
        }),
        prisma.product.findMany({
          where: { branchId },
          select: { id: true, stock: true, reorderLevel: true },
        }),
        prisma.stockLedger.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { productId: true, inQty: true, outQty: true },
        }),
      ]);

    const today = {
      sales: todaySalesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
      collections: todaySalesRows.reduce((sum, row) => sum + Number(row.paidAmount || 0), 0),
      purchase: todayPurchasesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
    };
    const yesterday = {
      sales: yesterdaySalesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
      collections: yesterdaySalesRows.reduce((sum, row) => sum + Number(row.paidAmount || 0), 0),
      purchase: yesterdayPurchasesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
    };

    const flowByProduct = new Map();
    for (const row of todayLedgers) {
      const productId = Number(row.productId);
      if (!flowByProduct.has(productId)) {
        flowByProduct.set(productId, { inQty: 0, outQty: 0 });
      }
      const existing = flowByProduct.get(productId);
      existing.inQty += Number(row.inQty || 0);
      existing.outQty += Number(row.outQty || 0);
      flowByProduct.set(productId, existing);
    }

    const lowStockToday = products.filter((p) => Number(p.stock || 0) <= Number(p.reorderLevel || 0)).length;
    const lowStockYesterdayApprox = products.filter((p) => {
      const flow = flowByProduct.get(Number(p.id)) || { inQty: 0, outQty: 0 };
      const openingStock = Number(p.stock || 0) - Number(flow.inQty || 0) + Number(flow.outQty || 0);
      return openingStock <= Number(p.reorderLevel || 0);
    }).length;

    const compare = (todayVal, yesterdayVal) => {
      const t = Number(todayVal || 0);
      const y = Number(yesterdayVal || 0);
      const diff = t - y;
      const pct = y === 0 ? (t === 0 ? 0 : 100) : (diff / y) * 100;
      return { today: t, yesterday: y, diff, pct };
    };

    res.json({
      sales: compare(today.sales, yesterday.sales),
      collections: compare(today.collections, yesterday.collections),
      purchase: compare(today.purchase, yesterday.purchase),
      lowStock: compare(lowStockToday, lowStockYesterdayApprox),
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getVatSummary = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    const outputVat = rows.reduce((sum, row) => sum + Number(row.vatAmount || 0), 0);
    const taxableSales = rows.reduce((sum, row) => sum + Number(row.taxableAmount || 0), 0);
    const grossSales = rows.reduce((sum, row) => sum + Number(row.grossAmount || 0), 0);
    const zeroVatSales = rows.filter((row) => Number(row.vatAmount || 0) <= 0).length;
    const inputVatInfo = await getInputVatFromPurchases(branchId, from, to);
    const inputVatTracked = Number(inputVatInfo.inputVat || 0);
    const netVatPayable = outputVat - inputVatTracked;
    res.json({
      from: from ? from.toISOString().slice(0, 10) : null,
      to: to ? to.toISOString().slice(0, 10) : null,
      salesCount: rows.length,
      zeroVatSales,
      taxableSales: Number(taxableSales.toFixed(2)),
      outputVat: Number(outputVat.toFixed(2)),
      grossSales: Number(grossSales.toFixed(2)),
      inputVatTracked: Number(inputVatTracked.toFixed(2)),
      netVatPayable: Number(netVatPayable.toFixed(2)),
      note:
        inputVatInfo.estimatedCount > 0
          ? `Input VAT is exact for ${inputVatInfo.exactCount} purchase(s) and estimated from product VAT rates for ${inputVatInfo.estimatedCount} older purchase(s).`
          : `Input VAT is computed from purchase records (${inputVatInfo.exactCount} purchase(s)).`,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getVatSalesRegister = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    res.json(rows);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportVatSalesRegisterCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    const csvRows = rows.map((row) => ({
      serial: row.serial,
      sale_id: row.saleId,
      invoice_no: row.invoiceNo,
      date: row.date,
      customer: row.customer,
      customer_phone: row.customerPhone,
      taxable_amount: Number(row.taxableAmount).toFixed(2),
      output_vat: Number(row.vatAmount).toFixed(2),
      gross_amount: Number(row.grossAmount).toFixed(2),
    }));
    const csv = toCSV(csvRows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="vat-sales-register.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportVatSalesRegisterPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    writePdfTableReport(
      res,
      "VAT Sales Register",
      [
        { key: "serial", label: "SL" },
        { key: "invoiceNo", label: "Invoice" },
        { key: "date", label: "Date" },
        { key: "customer", label: "Customer" },
        { key: "taxableAmount", label: "Taxable" },
        { key: "vatAmount", label: "VAT" },
        { key: "grossAmount", label: "Gross" },
      ],
      rows.map((row) => ({
        ...row,
        taxableAmount: Number(row.taxableAmount).toFixed(2),
        vatAmount: Number(row.vatAmount).toFixed(2),
        grossAmount: Number(row.grossAmount).toFixed(2),
      }))
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getAging = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    res.json({ customers, suppliers });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getStockValuation = async (req, res) => {
  try {
    const payload = await buildStockValuationPayload(req.branchId, req.query || {});
    res.json(payload);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationCSV = async (req, res) => {
  try {
    const payload = await buildStockValuationPayload(req.branchId, req.query || {});
    const rows = (payload.rows || []).map((p) => ({
      product_id: p.productId,
      product_name: p.name,
      category: p.category || "",
      stock: Number(p.stock || 0).toFixed(2),
      unit_cost: Number(p.unitCost || 0).toFixed(2),
      valuation: Number(p.valuation || 0).toFixed(2),
    }));
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="stock-valuation.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportAgingCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "CustomerDue",
        name: c.name,
        phone: c.phone || "",
        amount: c.balance,
      })),
      ...suppliers.map((s) => ({
        type: "SupplierPayable",
        name: s.name,
        phone: s.phone || "",
        amount: s.payableBalance,
      })),
    ];
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="aging-report.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationPDF = async (req, res) => {
  try {
    const payload = await buildStockValuationPayload(req.branchId, req.query || {});
    const rows = (payload.rows || []).map((p) => ({
      name: p.name,
      category: p.category || "-",
      stock: Number(p.stock || 0).toFixed(2),
      unitCost: Number(p.unitCost || 0).toFixed(2),
      valuation: Number(p.valuation || 0).toFixed(2),
    }));
    writePdfTableReport(
      res,
      "Stock Valuation Report",
      [
        { key: "name", label: "Product" },
        { key: "category", label: "Category" },
        { key: "stock", label: "Stock" },
        { key: "unitCost", label: "Unit Cost" },
        { key: "valuation", label: "Valuation" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

async function buildStockValuationPayload(branchId, query = {}) {
  const asOf = query.asOf ? new Date(`${query.asOf}T23:59:59.999Z`) : null;
  const category = String(query.category || "").trim();
  const warehouseId = query.warehouseId ? Number(query.warehouseId) : null;

  const products = await prisma.product.findMany({
    where: {
      branchId,
      ...(category ? { category: { contains: category } } : {}),
    },
    select: { id: true, name: true, category: true, stock: true, price: true },
    orderBy: { name: "asc" },
    take: 5000,
  });
  const productIds = products.map((p) => p.id);
  if (!productIds.length) {
    return { totalValue: 0, asOf: asOf ? asOf.toISOString().slice(0, 10) : null, category, warehouseId, rows: [] };
  }

  const shouldUseLedger = Boolean(asOf || warehouseId);
  if (!shouldUseLedger) {
    const rows = products.map((p) => ({
      productId: p.id,
      name: p.name,
      category: p.category || "",
      stock: Number(p.stock || 0),
      unitCost: Number(p.price || 0),
      valuation: Number((Number(p.stock || 0) * Number(p.price || 0)).toFixed(2)),
    }));
    const totalValue = rows.reduce((sum, r) => sum + Number(r.valuation || 0), 0);
    return {
      totalValue: Number(totalValue.toFixed(2)),
      asOf: null,
      category,
      warehouseId: null,
      rows,
    };
  }

  const ledgers = await prisma.stockLedger.findMany({
    where: {
      branchId,
      productId: { in: productIds },
      ...(warehouseId ? { warehouseId } : {}),
      ...(asOf ? { createdAt: { lte: asOf } } : {}),
    },
    select: { productId: true, inQty: true, outQty: true, unitCost: true },
    take: 50000,
  });
  const agg = new Map();
  for (const row of ledgers) {
    const pid = Number(row.productId);
    if (!agg.has(pid)) agg.set(pid, { qty: 0, value: 0 });
    const current = agg.get(pid);
    const inQty = Number(row.inQty || 0);
    const outQty = Number(row.outQty || 0);
    const unitCost = Number(row.unitCost || 0);
    current.qty += inQty - outQty;
    current.value += inQty * unitCost - outQty * unitCost;
    agg.set(pid, current);
  }

  const rows = products.map((p) => {
    const current = agg.get(p.id) || { qty: 0, value: 0 };
    const qty = Number(current.qty || 0);
    const value = Number(current.value || 0);
    const unitCost = qty > 0 ? value / qty : Number(p.price || 0);
    const valuation = qty > 0 ? value : 0;
    return {
      productId: p.id,
      name: p.name,
      category: p.category || "",
      stock: Number(qty.toFixed(2)),
      unitCost: Number(unitCost.toFixed(2)),
      valuation: Number(valuation.toFixed(2)),
    };
  });
  const totalValue = rows.reduce((sum, r) => sum + Number(r.valuation || 0), 0);
  return {
    totalValue: Number(totalValue.toFixed(2)),
    asOf: asOf ? asOf.toISOString().slice(0, 10) : null,
    category,
    warehouseId: warehouseId || null,
    rows,
  };
}

exports.exportAgingPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "Customer Due",
        name: c.name,
        phone: c.phone || "",
        amount: Number(c.balance).toFixed(2),
      })),
      ...suppliers.map((s) => ({
        type: "Supplier Payable",
        name: s.name,
        phone: s.phone || "",
        amount: Number(s.payableBalance).toFixed(2),
      })),
    ];
    writePdfTableReport(
      res,
      "Aging Report",
      [
        { key: "type", label: "Type" },
        { key: "name", label: "Name" },
        { key: "phone", label: "Phone" },
        { key: "amount", label: "Amount" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

function parseNumberOrDefault(value, fallback) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? n : fallback;
}

async function buildShrinkageControlPayload(branchId, query = {}) {
  const { from, to } = parseDateRange(query);
  const discountAlertMin = parseNumberOrDefault(query.discountAlertMin, 200);
  const returnAlertMin = parseNumberOrDefault(query.returnAlertMin, 200);
  const criticalAmount = parseNumberOrDefault(query.criticalAmount, 1000);
  const whereSales = buildSaleWhere(branchId, from, to);

  const sales = await prisma.sale.findMany({
    where: whereSales,
    include: {
      cashier: { select: { id: true, name: true, email: true } },
    },
    orderBy: { createdAt: "desc" },
    take: 5000,
  });
  const saleIds = sales.map((s) => Number(s.id));

  const returns = saleIds.length
    ? await prisma.saleReturn.findMany({
        where: {
          saleId: { in: saleIds },
          ...(from || to
            ? {
                createdAt: {
                  ...(from ? { gte: from } : {}),
                  ...(to ? { lte: to } : {}),
                },
              }
            : {}),
        },
        include: {
          sale: {
            select: {
              cashier: { select: { id: true, name: true, email: true } },
            },
          },
        },
        orderBy: { createdAt: "desc" },
        take: 5000,
      })
    : [];

  const approvalLogs = await prisma.auditLog.findMany({
    where: {
      action: { in: ["APPROVAL_DISCOUNT", "APPROVAL_PRICE_OVERRIDE", "APPROVAL_RETURN"] },
      ...(from || to
        ? {
            createdAt: {
              ...(from ? { gte: from } : {}),
              ...(to ? { lte: to } : {}),
            },
          }
        : {}),
    },
    include: {
      user: { select: { id: true, name: true, email: true } },
    },
    orderBy: { createdAt: "desc" },
    take: 5000,
  });

  const userMap = new Map();
  const ensureAgg = (user) => {
    const key = user?.id ? String(user.id) : "unknown";
    if (!userMap.has(key)) {
      userMap.set(key, {
        userId: user?.id || null,
        userName: user?.name || user?.email || "Unknown",
        saleCount: 0,
        grossSales: 0,
        discountCount: 0,
        discountAmount: 0,
        priceOverrideCount: 0,
        priceOverrideAmount: 0,
        returnCount: 0,
        returnAmount: 0,
      });
    }
    return userMap.get(key);
  };

  const events = [];
  for (const sale of sales) {
    const agg = ensureAgg(sale.cashier);
    agg.saleCount += 1;
    agg.grossSales += Number(sale.total || 0);
    if (Number(sale.discount || 0) > 0) {
      agg.discountCount += 1;
      agg.discountAmount += Number(sale.discount || 0);
    }
    if (Number(sale.discount || 0) >= discountAlertMin) {
      events.push({
        type: "HIGH_DISCOUNT_SALE",
        createdAt: sale.createdAt,
        userId: sale.cashier?.id || null,
        userName: sale.cashier?.name || sale.cashier?.email || "Unknown",
        amount: Number(sale.discount || 0),
        ref: sale.invoiceNo || `INV-${sale.id}`,
        note: `High discount on sale invoice ${sale.invoiceNo || `INV-${sale.id}`}`,
      });
    }
  }

  for (const row of returns) {
    const agg = ensureAgg(row.sale?.cashier);
    const amount = Number(row.amount || 0);
    agg.returnCount += 1;
    agg.returnAmount += amount;
    if (amount >= returnAlertMin) {
      events.push({
        type: "HIGH_RETURN",
        createdAt: row.createdAt,
        userId: row.sale?.cashier?.id || null,
        userName: row.sale?.cashier?.name || row.sale?.cashier?.email || "Unknown",
        amount,
        ref: row.saleId ? `SALE-${row.saleId}` : "-",
        note: "High value sale return",
      });
    }
  }

  for (const log of approvalLogs) {
    const agg = ensureAgg(log.user);
    const amount = Number(log.payload?.amount || 0);
    if (log.action === "APPROVAL_PRICE_OVERRIDE") {
      agg.priceOverrideCount += 1;
      agg.priceOverrideAmount += amount;
    } else if (log.action === "APPROVAL_DISCOUNT") {
      agg.discountCount += 1;
      agg.discountAmount += amount;
    } else if (log.action === "APPROVAL_RETURN") {
      agg.returnCount += 1;
      agg.returnAmount += amount;
    }
    events.push({
      type: log.action,
      createdAt: log.createdAt,
      userId: log.user?.id || null,
      userName: log.user?.name || log.user?.email || "Unknown",
      amount,
      ref: `${log.entity || ""}-${log.entityId || ""}` || "-",
      note: log.payload?.reason || "",
    });
  }

  const summaryRows = Array.from(userMap.values())
    .map((row) => {
      const gross = Number(row.grossSales || 0);
      const discountRate = gross > 0 ? (Number(row.discountAmount || 0) / gross) * 100 : 0;
      const returnRate = gross > 0 ? (Number(row.returnAmount || 0) / gross) * 100 : 0;
      const riskScore =
        Number(row.discountCount || 0) * 1.2 +
        Number(row.priceOverrideCount || 0) * 1.8 +
        Number(row.returnCount || 0) * 1.6 +
        discountRate * 0.4 +
        returnRate * 0.6;
      return {
        ...row,
        discountRate: Number(discountRate.toFixed(2)),
        returnRate: Number(returnRate.toFixed(2)),
        riskScore: Number(riskScore.toFixed(2)),
      };
    })
    .sort((a, b) => b.riskScore - a.riskScore);

  const eventRows = events
    .map((event) => ({ ...event, riskScore: Number(event.amount || 0) >= criticalAmount ? 10 : 5 }))
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 300);

  const totals = summaryRows.reduce(
    (acc, row) => {
      acc.totalCashiers += 1;
      acc.totalSales += Number(row.grossSales || 0);
      acc.totalDiscount += Number(row.discountAmount || 0);
      acc.totalReturns += Number(row.returnAmount || 0);
      acc.totalOverrides += Number(row.priceOverrideCount || 0);
      return acc;
    },
    { totalCashiers: 0, totalSales: 0, totalDiscount: 0, totalReturns: 0, totalOverrides: 0 }
  );

  return {
    from: from ? from.toISOString().slice(0, 10) : null,
    to: to ? to.toISOString().slice(0, 10) : null,
    thresholds: { discountAlertMin, returnAlertMin, criticalAmount },
    totals: {
      ...totals,
      totalSales: Number(totals.totalSales.toFixed(2)),
      totalDiscount: Number(totals.totalDiscount.toFixed(2)),
      totalReturns: Number(totals.totalReturns.toFixed(2)),
    },
    summaryRows,
    eventRows,
  };
}

exports.getShrinkageControlReport = async (req, res) => {
  try {
    const payload = await buildShrinkageControlPayload(req.branchId, req.query || {});
    res.json(payload);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportShrinkageControlCSV = async (req, res) => {
  try {
    const payload = await buildShrinkageControlPayload(req.branchId, req.query || {});
    const rows = (payload.summaryRows || []).map((row) => ({
      user_name: row.userName,
      sale_count: row.saleCount,
      gross_sales: Number(row.grossSales || 0).toFixed(2),
      discount_count: row.discountCount,
      discount_amount: Number(row.discountAmount || 0).toFixed(2),
      price_override_count: row.priceOverrideCount,
      return_count: row.returnCount,
      return_amount: Number(row.returnAmount || 0).toFixed(2),
      discount_rate_pct: Number(row.discountRate || 0).toFixed(2),
      return_rate_pct: Number(row.returnRate || 0).toFixed(2),
      risk_score: Number(row.riskScore || 0).toFixed(2),
    }));
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="shrinkage-risk-summary.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportShrinkageControlPDF = async (req, res) => {
  try {
    const payload = await buildShrinkageControlPayload(req.branchId, req.query || {});
    writePdfTableReport(
      res,
      "Shrinkage Risk Summary",
      [
        { key: "userName", label: "Cashier/User" },
        { key: "saleCount", label: "Sales" },
        { key: "discountAmount", label: "Discount" },
        { key: "returnAmount", label: "Returns" },
        { key: "riskScore", label: "Risk Score" },
      ],
      (payload.summaryRows || []).map((row) => ({
        userName: row.userName,
        saleCount: row.saleCount,
        discountAmount: Number(row.discountAmount || 0).toFixed(2),
        returnAmount: Number(row.returnAmount || 0).toFixed(2),
        riskScore: Number(row.riskScore || 0).toFixed(2),
      }))
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getStaffPerformanceScorecard = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const saleWhere = buildSaleWhere(branchId, from, to);
    const sales = await prisma.sale.findMany({
      where: saleWhere,
      include: {
        cashier: { select: { id: true, name: true, email: true } },
      },
      orderBy: { createdAt: "desc" },
      take: 5000,
    });
    const saleIds = sales.map((s) => Number(s.id));
    const returns = saleIds.length
      ? await prisma.saleReturn.findMany({
          where: { saleId: { in: saleIds } },
          include: { sale: { select: { cashier: { select: { id: true, name: true, email: true } } } } },
          take: 5000,
        })
      : [];
    const approvals = await prisma.auditLog.findMany({
      where: {
        action: { in: ["APPROVAL_DISCOUNT", "APPROVAL_PRICE_OVERRIDE", "APPROVAL_RETURN"] },
        ...(from || to
          ? {
              createdAt: {
                ...(from ? { gte: from } : {}),
                ...(to ? { lte: to } : {}),
              },
            }
          : {}),
      },
      include: { user: { select: { id: true, name: true, email: true } } },
      take: 5000,
    });

    const byUser = new Map();
    const ensure = (user) => {
      const key = user?.id ? String(user.id) : "unknown";
      if (!byUser.has(key)) {
        byUser.set(key, {
          userId: user?.id || null,
          userName: user?.name || user?.email || "Unknown",
          invoiceCount: 0,
          grossSales: 0,
          totalDiscount: 0,
          returnCount: 0,
          returnAmount: 0,
          overrideCount: 0,
          avgBill: 0,
          riskScore: 0,
        });
      }
      return byUser.get(key);
    };

    for (const sale of sales) {
      const row = ensure(sale.cashier);
      row.invoiceCount += 1;
      row.grossSales += Number(sale.total || 0);
      row.totalDiscount += Number(sale.discount || 0);
    }
    for (const ret of returns) {
      const row = ensure(ret.sale?.cashier);
      row.returnCount += 1;
      row.returnAmount += Number(ret.amount || 0);
    }
    for (const approval of approvals) {
      const row = ensure(approval.user);
      if (approval.action === "APPROVAL_PRICE_OVERRIDE") row.overrideCount += 1;
      if (approval.action === "APPROVAL_RETURN") row.returnCount += 1;
      if (approval.action === "APPROVAL_DISCOUNT") row.totalDiscount += Number(approval.payload?.amount || 0);
    }

    const rows = Array.from(byUser.values())
      .map((row) => {
        const invoiceCount = Number(row.invoiceCount || 0);
        const gross = Number(row.grossSales || 0);
        const avgBill = invoiceCount > 0 ? gross / invoiceCount : 0;
        const discountRate = gross > 0 ? (Number(row.totalDiscount || 0) / gross) * 100 : 0;
        const returnRate = gross > 0 ? (Number(row.returnAmount || 0) / gross) * 100 : 0;
        const riskScore = Number(
          (Number(row.returnCount || 0) * 1.8 + Number(row.overrideCount || 0) * 1.5 + discountRate * 0.4 + returnRate * 0.7).toFixed(2)
        );
        return {
          ...row,
          avgBill: Number(avgBill.toFixed(2)),
          discountRate: Number(discountRate.toFixed(2)),
          returnRate: Number(returnRate.toFixed(2)),
          riskScore,
        };
      })
      .sort((a, b) => Number(b.grossSales || 0) - Number(a.grossSales || 0));

    res.json({
      from: from ? from.toISOString().slice(0, 10) : null,
      to: to ? to.toISOString().slice(0, 10) : null,
      summary: {
        staffCount: rows.length,
        totalSales: Number(rows.reduce((sum, r) => sum + Number(r.grossSales || 0), 0).toFixed(2)),
        totalInvoices: rows.reduce((sum, r) => sum + Number(r.invoiceCount || 0), 0),
      },
      rows,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getAuditActivityTrail = async (req, res) => {
  try {
    const { from, to } = parseDateRange(req.query || {});
    const action = String(req.query?.action || "").trim();
    const entity = String(req.query?.entity || "").trim();
    const limitRaw = Number(req.query?.limit || 300);
    const limit = Number.isFinite(limitRaw) ? Math.min(Math.max(limitRaw, 1), 1000) : 300;

    const where = {
      ...(from || to
        ? {
            createdAt: {
              ...(from ? { gte: from } : {}),
              ...(to ? { lte: to } : {}),
            },
          }
        : {}),
      ...(action ? { action: { contains: action } } : {}),
      ...(entity ? { entity: { contains: entity } } : {}),
    };

    const logs = await prisma.auditLog.findMany({
      where,
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true,
            role: { select: { name: true } },
          },
        },
      },
      orderBy: { createdAt: "desc" },
      take: limit,
    });

    const rows = logs.map((log) => ({
      id: log.id,
      createdAt: log.createdAt,
      action: log.action || "",
      entity: log.entity || "",
      entityId: log.entityId,
      userId: log.userId,
      userName: log.user?.name || log.user?.email || "System",
      userRole: log.user?.role?.name || "-",
      payload: log.payload || null,
    }));

    res.json({
      from: from ? from.toISOString().slice(0, 10) : null,
      to: to ? to.toISOString().slice(0, 10) : null,
      count: rows.length,
      rows,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

async function getChequeLedgerRows(branchId, query = {}) {
  const { from, to } = parseDateRange(query || {});
  const direction = String(query.direction || "").trim().toUpperCase();
  const status = String(query.status || "").trim().toUpperCase();
  const onlyMismatched =
    String(query.onlyMismatched || "").trim() === "1" ||
    String(query.onlyMismatched || "").trim().toLowerCase() === "true";
  const where = { branchId };
  if (from || to) {
    where.createdAt = {
      ...(from ? { gte: from } : {}),
      ...(to ? { lte: to } : {}),
    };
  }
  if (direction) where.direction = direction;
  if (status) where.status = status;

  const journals = await prisma.journal.findMany({
    where: {
      branchId,
      refType: { in: ["CHEQUE_CLEAR", "CHEQUE_BOUNCE"] },
      ...(from || to
        ? {
            createdAt: {
              ...(from ? { gte: from } : {}),
              ...(to ? { lte: to } : {}),
            },
          }
        : {}),
    },
    include: {
      lines: { include: { account: { select: { code: true, name: true } } } },
    },
    orderBy: { createdAt: "desc" },
    take: 2000,
  });
  const chequeIds = [...new Set(journals.map((j) => Number(j.refId || 0)).filter(Boolean))];
  const cheques = chequeIds.length
    ? await prisma.cheque.findMany({
        where: { branchId, id: { in: chequeIds }, ...(direction ? { direction } : {}), ...(status ? { status } : {}) },
        select: {
          id: true,
          chequeNo: true,
          bankName: true,
          direction: true,
          status: true,
          amount: true,
          createdAt: true,
          chequeDate: true,
          depositDate: true,
          clearedDate: true,
          bounceDate: true,
          bounceReason: true,
          bounceFee: true,
          drawerName: true,
          payeeName: true,
        },
      })
    : [];
  const chequeMap = new Map(cheques.map((c) => [c.id, c]));

  const rows = [];
  const journalTotals = new Map();
  for (const journal of journals) {
    const chequeId = Number(journal.refId || 0);
    const cheque = chequeMap.get(chequeId);
    if (!cheque) continue;
    for (const line of journal.lines || []) {
      const journalId = Number(journal.id || 0);
      if (!journalTotals.has(journalId)) {
        journalTotals.set(journalId, { debit: 0, credit: 0 });
      }
      const totals = journalTotals.get(journalId);
      totals.debit += Number(line.debit || 0);
      totals.credit += Number(line.credit || 0);
      journalTotals.set(journalId, totals);
      rows.push({
        journalId: journal.id,
        journalDate: journal.createdAt.toISOString(),
        entryType: journal.refType,
        chequeId: cheque.id,
        chequeNo: cheque.chequeNo,
        bankName: cheque.bankName,
        direction: cheque.direction,
        status: cheque.status,
        chequeAmount: Number(cheque.amount || 0),
        chequeDate: cheque.chequeDate ? cheque.chequeDate.toISOString().slice(0, 10) : "",
        depositDate: cheque.depositDate ? cheque.depositDate.toISOString().slice(0, 10) : "",
        clearedDate: cheque.clearedDate ? cheque.clearedDate.toISOString().slice(0, 10) : "",
        bounceDate: cheque.bounceDate ? cheque.bounceDate.toISOString().slice(0, 10) : "",
        bounceReason: cheque.bounceReason || "",
        bounceFee: Number(cheque.bounceFee || 0),
        partyName: cheque.direction === "RECEIVED" ? cheque.drawerName || "" : cheque.payeeName || "",
        accountCode: line.account?.code || "",
        accountName: line.account?.name || "",
        debit: Number(line.debit || 0),
        credit: Number(line.credit || 0),
        narration: journal.narration || "",
      });
    }
  }
  if (!onlyMismatched) return rows;
  const mismatchedJournalIds = new Set(
    [...journalTotals.entries()]
      .filter(([, totals]) => Math.abs(Number(totals.debit || 0) - Number(totals.credit || 0)) > 0.001)
      .map(([journalId]) => Number(journalId))
  );
  return rows.filter((row) => mismatchedJournalIds.has(Number(row.journalId || 0)));
}

async function getChequeLedgerSummary(branchId, query = {}) {
  const { from, to } = parseDateRange(query || {});
  const direction = String(query.direction || "").trim().toUpperCase();
  const status = String(query.status || "").trim().toUpperCase();

  const journals = await prisma.journal.findMany({
    where: {
      branchId,
      refType: { in: ["CHEQUE_CLEAR", "CHEQUE_BOUNCE"] },
      ...(from || to
        ? {
            createdAt: {
              ...(from ? { gte: from } : {}),
              ...(to ? { lte: to } : {}),
            },
          }
        : {}),
    },
    include: {
      lines: { select: { debit: true, credit: true } },
    },
    orderBy: { createdAt: "desc" },
    take: 2000,
  });

  const chequeIds = [...new Set(journals.map((j) => Number(j.refId || 0)).filter(Boolean))];
  const cheques = chequeIds.length
    ? await prisma.cheque.findMany({
        where: {
          branchId,
          id: { in: chequeIds },
          ...(direction ? { direction } : {}),
          ...(status ? { status } : {}),
        },
        select: { id: true },
      })
    : [];
  const chequeIdSet = new Set(cheques.map((c) => Number(c.id)));

  const filteredJournals = journals.filter((j) => chequeIdSet.has(Number(j.refId || 0)));
  let totalDebit = 0;
  let totalCredit = 0;
  let mismatchedJournals = 0;
  for (const journal of filteredJournals) {
    let debit = 0;
    let credit = 0;
    for (const line of journal.lines || []) {
      const d = Number(line.debit || 0);
      const c = Number(line.credit || 0);
      debit += d;
      credit += c;
      totalDebit += d;
      totalCredit += c;
    }
    if (Math.abs(debit - credit) > 0.001) mismatchedJournals += 1;
  }

  return {
    journalCount: filteredJournals.length,
    mismatchedJournalCount: mismatchedJournals,
    totalDebit: Number(totalDebit.toFixed(2)),
    totalCredit: Number(totalCredit.toFixed(2)),
  };
}

exports.getChequeLedger = async (req, res) => {
  try {
    const rows = await getChequeLedgerRows(req.branchId, req.query || {});
    const summary = await getChequeLedgerSummary(req.branchId, req.query || {});
    res.json({
      summary,
      rows,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportChequeLedgerCSV = async (req, res) => {
  try {
    const rows = await getChequeLedgerRows(req.branchId, req.query || {});
    const csv = toCSV(
      rows.map((row) => ({
        journal_id: row.journalId,
        journal_date: row.journalDate,
        entry_type: row.entryType,
        cheque_id: row.chequeId,
        cheque_no: row.chequeNo,
        bank_name: row.bankName,
        direction: row.direction,
        status: row.status,
        cheque_amount: Number(row.chequeAmount || 0).toFixed(2),
        cheque_date: row.chequeDate,
        deposit_date: row.depositDate,
        cleared_date: row.clearedDate,
        bounce_date: row.bounceDate,
        bounce_reason: row.bounceReason,
        bounce_fee: Number(row.bounceFee || 0).toFixed(2),
        party_name: row.partyName,
        account_code: row.accountCode,
        account_name: row.accountName,
        debit: Number(row.debit || 0).toFixed(2),
        credit: Number(row.credit || 0).toFixed(2),
        narration: row.narration,
      }))
    );
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="cheque-ledger.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportChequeLedgerPDF = async (req, res) => {
  try {
    const rows = await getChequeLedgerRows(req.branchId, req.query || {});
    writePdfTableReport(
      res,
      "Cheque Ledger",
      [
        { key: "journalDate", label: "Date" },
        { key: "entryType", label: "Entry" },
        { key: "chequeNo", label: "Cheque" },
        { key: "direction", label: "Direction" },
        { key: "accountCode", label: "A/C" },
        { key: "debit", label: "Debit" },
        { key: "credit", label: "Credit" },
      ],
      rows.map((row) => ({
        ...row,
        journalDate: row.journalDate ? new Date(row.journalDate).toLocaleString() : "",
        debit: Number(row.debit || 0).toFixed(2),
        credit: Number(row.credit || 0).toFixed(2),
      }))
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
