const prisma = require("../../utils/prisma");
const PDFDocument = require("pdfkit");

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = Object.keys(rows[0]);
  const lines = [headers.join(",")];
  for (const row of rows) {
    const values = headers.map((h) => {
      const value = row[h] == null ? "" : String(row[h]).replaceAll('"', '""');
      return `"${value}"`;
    });
    lines.push(values.join(","));
  }
  return lines.join("\n");
}

function writePdfTableReport(res, title, columns, rows) {
  const doc = new PDFDocument({ margin: 40, size: "A4", bufferPages: true });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${title.toLowerCase().replaceAll(" ", "-")}.pdf"`);
  doc.pipe(res);

  const storeName = process.env.REPORT_STORE_NAME || "BD Smart POS";
  const storeAddress = process.env.REPORT_STORE_ADDRESS || "Dhaka, Bangladesh";
  const storePhone = process.env.REPORT_STORE_PHONE || "";
  const footerText = process.env.REPORT_FOOTER_TEXT || "Generated by BD Smart POS";
  const generatedAt = new Date().toLocaleString("bn-BD");

  doc.fontSize(16).font("Helvetica-Bold").text(storeName, { align: "center" });
  doc.moveDown(0.1);
  doc.fontSize(10).font("Helvetica").text(storeAddress, { align: "center" });
  if (storePhone) {
    doc.text(`Phone: ${storePhone}`, { align: "center" });
  }
  doc.moveDown(0.3);
  doc.fontSize(14).font("Helvetica-Bold").text(title, { align: "center" });
  doc.fontSize(10).font("Helvetica").text(`Generated: ${generatedAt}`, { align: "center" });
  doc.moveDown(1);

  const startX = 40;
  let y = doc.y;
  const tableWidth = 515;
  const colWidth = tableWidth / columns.length;

  doc.fontSize(10).font("Helvetica-Bold");
  columns.forEach((col, idx) => {
    doc.text(col.label, startX + idx * colWidth, y, { width: colWidth, align: "left" });
  });
  y += 18;
  doc.moveTo(startX, y - 4).lineTo(startX + tableWidth, y - 4).stroke("#888");

  doc.font("Helvetica");
  rows.forEach((row) => {
    if (y > 760) {
      doc.addPage();
      y = 50;
    }
    columns.forEach((col, idx) => {
      const value = row[col.key] == null ? "" : String(row[col.key]);
      doc.text(value, startX + idx * colWidth, y, { width: colWidth, align: "left" });
    });
    y += 18;
  });

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(9).fillColor("#666");
    doc.text(
      `${footerText} | Page ${i + 1} of ${range.count}`,
      40,
      810,
      { align: "center", width: 515 }
    );
  }

  doc.end();
}

function parseDateRange(query = {}) {
  const from = query.from ? new Date(`${query.from}T00:00:00.000Z`) : null;
  const to = query.to ? new Date(`${query.to}T23:59:59.999Z`) : null;
  return { from, to };
}

function buildSaleWhere(branchId, from, to) {
  const where = { branchId };
  if (from || to) {
    where.createdAt = {};
    if (from) where.createdAt.gte = from;
    if (to) where.createdAt.lte = to;
  }
  return where;
}

async function getVatSalesRows(branchId, from, to) {
  const sales = await prisma.sale.findMany({
    where: buildSaleWhere(branchId, from, to),
    include: {
      customer: { select: { name: true, phone: true } },
    },
    orderBy: { createdAt: "asc" },
  });
  return sales.map((sale, idx) => {
    const total = Number(sale.total || 0);
    const vatAmount = Number(sale.vatAmount || 0);
    const taxableAmount = Math.max(0, total - vatAmount);
    return {
      serial: idx + 1,
      saleId: sale.id,
      invoiceNo: sale.invoiceNo || `INV-${sale.id}`,
      date: sale.createdAt.toISOString().slice(0, 10),
      customer: sale.customer?.name || "Walk-in",
      customerPhone: sale.customer?.phone || "-",
      taxableAmount: Number(taxableAmount.toFixed(2)),
      vatAmount: Number(vatAmount.toFixed(2)),
      grossAmount: Number(total.toFixed(2)),
    };
  });
}

async function getInputVatFromPurchases(branchId, from, to) {
  const purchases = await prisma.purchase.findMany({
    where: buildSaleWhere(branchId, from, to),
    include: {
      items: {
        include: {
          product: { select: { vatRate: true } },
        },
      },
    },
    orderBy: { createdAt: "asc" },
  });
  if (!purchases.length) {
    return { inputVat: 0, estimatedCount: 0, exactCount: 0 };
  }
  const purchaseIds = purchases.map((p) => p.id);
  const purchaseAuditLogs = await prisma.auditLog.findMany({
    where: {
      action: "PURCHASE_CREATE",
      entity: "Purchase",
      entityId: { in: purchaseIds },
    },
    select: { entityId: true, payload: true },
  });
  const inputVatByPurchaseId = new Map(
    purchaseAuditLogs
      .filter((x) => x.entityId != null)
      .map((x) => [Number(x.entityId), Number(x.payload?.inputVat || 0)])
  );

  let inputVat = 0;
  let estimatedCount = 0;
  let exactCount = 0;
  for (const purchase of purchases) {
    const purchaseId = Number(purchase.id);
    if (inputVatByPurchaseId.has(purchaseId)) {
      inputVat += Number(inputVatByPurchaseId.get(purchaseId) || 0);
      exactCount += 1;
      continue;
    }
    const estimated = (purchase.items || []).reduce((sum, item) => {
      const qty = Number(item.qty || 0);
      const cost = Number(item.cost || 0);
      const vatRate = Number(item.product?.vatRate || 0);
      if (vatRate <= 0) return sum;
      return sum + (qty * cost * vatRate) / 100;
    }, 0);
    inputVat += estimated;
    estimatedCount += 1;
  }
  return {
    inputVat: Number(inputVat.toFixed(2)),
    estimatedCount,
    exactCount,
  };
}

exports.getDashboard = async (req, res) => {
  try {
    const branchId = req.branchId;
    const start = new Date();
    start.setHours(0, 0, 0, 0);
    const sales = await prisma.sale.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const purchases = await prisma.purchase.findMany({
      where: { branchId, createdAt: { gte: start } },
    });
    const products = await prisma.product.findMany({ where: { branchId } });
    const stockAlerts = products.filter((p) => p.stock <= p.reorderLevel).length;
    const totals = {
      sales: sales.reduce((a, x) => a + x.total, 0),
      collections: sales.reduce((a, x) => a + x.paidAmount, 0),
      purchase: purchases.reduce((a, x) => a + x.total, 0),
      stockAlerts,
    };
    res.json(totals);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getDashboardTrends = async (req, res) => {
  try {
    const branchId = req.branchId;
    const now = new Date();
    const startToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const startYesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);

    const [todaySalesRows, yesterdaySalesRows, todayPurchasesRows, yesterdayPurchasesRows, products, todayLedgers] =
      await Promise.all([
        prisma.sale.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { total: true, paidAmount: true },
        }),
        prisma.sale.findMany({
          where: { branchId, createdAt: { gte: startYesterday, lt: startToday } },
          select: { total: true, paidAmount: true },
        }),
        prisma.purchase.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { total: true },
        }),
        prisma.purchase.findMany({
          where: { branchId, createdAt: { gte: startYesterday, lt: startToday } },
          select: { total: true },
        }),
        prisma.product.findMany({
          where: { branchId },
          select: { id: true, stock: true, reorderLevel: true },
        }),
        prisma.stockLedger.findMany({
          where: { branchId, createdAt: { gte: startToday } },
          select: { productId: true, inQty: true, outQty: true },
        }),
      ]);

    const today = {
      sales: todaySalesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
      collections: todaySalesRows.reduce((sum, row) => sum + Number(row.paidAmount || 0), 0),
      purchase: todayPurchasesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
    };
    const yesterday = {
      sales: yesterdaySalesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
      collections: yesterdaySalesRows.reduce((sum, row) => sum + Number(row.paidAmount || 0), 0),
      purchase: yesterdayPurchasesRows.reduce((sum, row) => sum + Number(row.total || 0), 0),
    };

    const flowByProduct = new Map();
    for (const row of todayLedgers) {
      const productId = Number(row.productId);
      if (!flowByProduct.has(productId)) {
        flowByProduct.set(productId, { inQty: 0, outQty: 0 });
      }
      const existing = flowByProduct.get(productId);
      existing.inQty += Number(row.inQty || 0);
      existing.outQty += Number(row.outQty || 0);
      flowByProduct.set(productId, existing);
    }

    const lowStockToday = products.filter((p) => Number(p.stock || 0) <= Number(p.reorderLevel || 0)).length;
    const lowStockYesterdayApprox = products.filter((p) => {
      const flow = flowByProduct.get(Number(p.id)) || { inQty: 0, outQty: 0 };
      const openingStock = Number(p.stock || 0) - Number(flow.inQty || 0) + Number(flow.outQty || 0);
      return openingStock <= Number(p.reorderLevel || 0);
    }).length;

    const compare = (todayVal, yesterdayVal) => {
      const t = Number(todayVal || 0);
      const y = Number(yesterdayVal || 0);
      const diff = t - y;
      const pct = y === 0 ? (t === 0 ? 0 : 100) : (diff / y) * 100;
      return { today: t, yesterday: y, diff, pct };
    };

    res.json({
      sales: compare(today.sales, yesterday.sales),
      collections: compare(today.collections, yesterday.collections),
      purchase: compare(today.purchase, yesterday.purchase),
      lowStock: compare(lowStockToday, lowStockYesterdayApprox),
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getVatSummary = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    const outputVat = rows.reduce((sum, row) => sum + Number(row.vatAmount || 0), 0);
    const taxableSales = rows.reduce((sum, row) => sum + Number(row.taxableAmount || 0), 0);
    const grossSales = rows.reduce((sum, row) => sum + Number(row.grossAmount || 0), 0);
    const zeroVatSales = rows.filter((row) => Number(row.vatAmount || 0) <= 0).length;
    const inputVatInfo = await getInputVatFromPurchases(branchId, from, to);
    const inputVatTracked = Number(inputVatInfo.inputVat || 0);
    const netVatPayable = outputVat - inputVatTracked;
    res.json({
      from: from ? from.toISOString().slice(0, 10) : null,
      to: to ? to.toISOString().slice(0, 10) : null,
      salesCount: rows.length,
      zeroVatSales,
      taxableSales: Number(taxableSales.toFixed(2)),
      outputVat: Number(outputVat.toFixed(2)),
      grossSales: Number(grossSales.toFixed(2)),
      inputVatTracked: Number(inputVatTracked.toFixed(2)),
      netVatPayable: Number(netVatPayable.toFixed(2)),
      note:
        inputVatInfo.estimatedCount > 0
          ? `Input VAT is exact for ${inputVatInfo.exactCount} purchase(s) and estimated from product VAT rates for ${inputVatInfo.estimatedCount} older purchase(s).`
          : `Input VAT is computed from purchase records (${inputVatInfo.exactCount} purchase(s)).`,
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getVatSalesRegister = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    res.json(rows);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportVatSalesRegisterCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    const csvRows = rows.map((row) => ({
      serial: row.serial,
      sale_id: row.saleId,
      invoice_no: row.invoiceNo,
      date: row.date,
      customer: row.customer,
      customer_phone: row.customerPhone,
      taxable_amount: Number(row.taxableAmount).toFixed(2),
      output_vat: Number(row.vatAmount).toFixed(2),
      gross_amount: Number(row.grossAmount).toFixed(2),
    }));
    const csv = toCSV(csvRows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="vat-sales-register.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportVatSalesRegisterPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const { from, to } = parseDateRange(req.query || {});
    const rows = await getVatSalesRows(branchId, from, to);
    writePdfTableReport(
      res,
      "VAT Sales Register",
      [
        { key: "serial", label: "SL" },
        { key: "invoiceNo", label: "Invoice" },
        { key: "date", label: "Date" },
        { key: "customer", label: "Customer" },
        { key: "taxableAmount", label: "Taxable" },
        { key: "vatAmount", label: "VAT" },
        { key: "grossAmount", label: "Gross" },
      ],
      rows.map((row) => ({
        ...row,
        taxableAmount: Number(row.taxableAmount).toFixed(2),
        vatAmount: Number(row.vatAmount).toFixed(2),
        grossAmount: Number(row.grossAmount).toFixed(2),
      }))
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getAging = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    res.json({ customers, suppliers });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getStockValuation = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      productId: p.id,
      name: p.name,
      stock: p.stock,
      unitCost: p.price,
      valuation: Number(p.stock) * Number(p.price),
    }));
    const totalValue = rows.reduce((sum, r) => sum + r.valuation, 0);
    res.json({ totalValue, rows });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      product_id: p.id,
      product_name: p.name,
      stock: p.stock,
      unit_cost: p.price,
      valuation: Number(p.stock) * Number(p.price),
    }));
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="stock-valuation.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportAgingCSV = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "CustomerDue",
        name: c.name,
        phone: c.phone || "",
        amount: c.balance,
      })),
      ...suppliers.map((s) => ({
        type: "SupplierPayable",
        name: s.name,
        phone: s.phone || "",
        amount: s.payableBalance,
      })),
    ];
    const csv = toCSV(rows);
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", 'attachment; filename="aging-report.csv"');
    res.send(csv);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportStockValuationPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const products = await prisma.product.findMany({ where: { branchId } });
    const rows = products.map((p) => ({
      name: p.name,
      stock: p.stock,
      unitCost: Number(p.price).toFixed(2),
      valuation: (Number(p.stock) * Number(p.price)).toFixed(2),
    }));
    writePdfTableReport(
      res,
      "Stock Valuation Report",
      [
        { key: "name", label: "Product" },
        { key: "stock", label: "Stock" },
        { key: "unitCost", label: "Unit Cost" },
        { key: "valuation", label: "Valuation" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.exportAgingPDF = async (req, res) => {
  try {
    const branchId = req.branchId;
    const customers = await prisma.customer.findMany({
      where: { branchId, balance: { gt: 0 } },
      orderBy: { balance: "desc" },
    });
    const suppliers = await prisma.supplier.findMany({
      where: { branchId, payableBalance: { gt: 0 } },
      orderBy: { payableBalance: "desc" },
    });
    const rows = [
      ...customers.map((c) => ({
        type: "Customer Due",
        name: c.name,
        phone: c.phone || "",
        amount: Number(c.balance).toFixed(2),
      })),
      ...suppliers.map((s) => ({
        type: "Supplier Payable",
        name: s.name,
        phone: s.phone || "",
        amount: Number(s.payableBalance).toFixed(2),
      })),
    ];
    writePdfTableReport(
      res,
      "Aging Report",
      [
        { key: "type", label: "Type" },
        { key: "name", label: "Name" },
        { key: "phone", label: "Phone" },
        { key: "amount", label: "Amount" },
      ],
      rows
    );
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
