-- Withholding-tax compliance fields (AIT / VDS) on Bangladesh supplier payments.
-- Idempotent.

SET @db := DATABASE();

-- Supplier
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND COLUMN_NAME = 'tinNumber') > 0, 'SELECT 1', 'ALTER TABLE `Supplier` ADD COLUMN `tinNumber` VARCHAR(32) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND COLUMN_NAME = 'binNumber') > 0, 'SELECT 1', 'ALTER TABLE `Supplier` ADD COLUMN `binNumber` VARCHAR(32) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND COLUMN_NAME = 'taxCategory') > 0, 'SELECT 1', 'ALTER TABLE `Supplier` ADD COLUMN `taxCategory` VARCHAR(64) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND COLUMN_NAME = 'withholdingExempt') > 0, 'SELECT 1', 'ALTER TABLE `Supplier` ADD COLUMN `withholdingExempt` BOOLEAN NOT NULL DEFAULT false'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND COLUMN_NAME = 'withholdingNote') > 0, 'SELECT 1', 'ALTER TABLE `Supplier` ADD COLUMN `withholdingNote` VARCHAR(191) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Supplier' AND INDEX_NAME = 'Supplier_branchId_taxCategory_idx') > 0, 'SELECT 1', 'CREATE INDEX `Supplier_branchId_taxCategory_idx` ON `Supplier` (`branchId`, `taxCategory`)'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- PaymentVoucher
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'aitRate') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `aitRate` DOUBLE NOT NULL DEFAULT 0'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'aitAmount') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `aitAmount` DOUBLE NOT NULL DEFAULT 0'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'vdsRate') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `vdsRate` DOUBLE NOT NULL DEFAULT 0'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'vdsAmount') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `vdsAmount` DOUBLE NOT NULL DEFAULT 0'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'netPaid') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `netPaid` DOUBLE NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'taxCategory') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `taxCategory` VARCHAR(64) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'withholdingNote') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `withholdingNote` VARCHAR(255) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'mushak66DocumentNo') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `mushak66DocumentNo` VARCHAR(64) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'branchId_for_index_only') > 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` ADD COLUMN `branchId_for_index_only` INTEGER NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND COLUMN_NAME = 'branchId_for_index_only') = 0, 'SELECT 1', 'ALTER TABLE `PaymentVoucher` DROP COLUMN `branchId_for_index_only`'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND INDEX_NAME = 'PaymentVoucher_branchId_createdAt_idx') > 0, 'SELECT 1', 'CREATE INDEX `PaymentVoucher_branchId_createdAt_idx` ON `PaymentVoucher` (`branchId`, `createdAt`)'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'PaymentVoucher' AND INDEX_NAME = 'PaymentVoucher_branchId_supplierId_idx') > 0, 'SELECT 1', 'CREATE INDEX `PaymentVoucher_branchId_supplierId_idx` ON `PaymentVoucher` (`branchId`, `supplierId`)'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
