-- NBR Mushak 6.3 (Tax Invoice) compliance fields.
-- Idempotent for databases where columns/indexes were added out-of-band.

SET @db := DATABASE();

-- Product columns
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Product' AND COLUMN_NAME = 'nameBn') > 0, 'SELECT 1', 'ALTER TABLE `Product` ADD COLUMN `nameBn` VARCHAR(191) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Product' AND COLUMN_NAME = 'hsCode') > 0, 'SELECT 1', 'ALTER TABLE `Product` ADD COLUMN `hsCode` VARCHAR(32) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Product' AND COLUMN_NAME = 'unitOfMeasure') > 0, 'SELECT 1', CONCAT('ALTER TABLE `Product` ADD COLUMN `unitOfMeasure` VARCHAR(16) NULL DEFAULT ', CHAR(39), 'PCS', CHAR(39))));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- Sale columns
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Sale' AND COLUMN_NAME = 'nbrXmlPayload') > 0, 'SELECT 1', 'ALTER TABLE `Sale` ADD COLUMN `nbrXmlPayload` MEDIUMTEXT NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Sale' AND COLUMN_NAME = 'nbrXmlHash') > 0, 'SELECT 1', 'ALTER TABLE `Sale` ADD COLUMN `nbrXmlHash` VARCHAR(64) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Sale' AND COLUMN_NAME = 'nbrEmittedAt') > 0, 'SELECT 1', 'ALTER TABLE `Sale` ADD COLUMN `nbrEmittedAt` DATETIME(3) NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- Indexes
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Sale' AND INDEX_NAME = 'Sale_branchId_nbrEmittedAt_idx') > 0, 'SELECT 1', 'CREATE INDEX `Sale_branchId_nbrEmittedAt_idx` ON `Sale` (`branchId`, `nbrEmittedAt`)'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Product' AND INDEX_NAME = 'Product_branchId_hsCode_idx') > 0, 'SELECT 1', 'CREATE INDEX `Product_branchId_hsCode_idx` ON `Product` (`branchId`, `hsCode`)'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
