SET @db := DATABASE();
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Shift' AND COLUMN_NAME = 'closingDenomination') > 0, 'SELECT 1', 'ALTER TABLE `Shift` ADD COLUMN `closingDenomination` JSON NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
