/** Bangladesh districts (64) for delivery address dropdowns */
export const BD_DISTRICTS = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barishal",
  "Bhola",
  "Bogura",
  "Brahmanbaria",
  "Chandpur",
  "Chattogram",
  "Chuadanga",
  "Cox's Bazar",
  "Cumilla",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jamalpur",
  "Jashore",
  "Jhalokati",
  "Jhenaidah",
  "Joypurhat",
  "Khagrachhari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Meherpur",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narail",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Netrokona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangamati",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];

export const CUSTOMER_TYPES = [
  { value: "RETAIL", labelKey: "custTypeRetail" },
  { value: "WHOLESALE", labelKey: "custTypeWholesale" },
  { value: "INSTITUTION", labelKey: "custTypeInstitution" },
];

export const ORDER_SOURCES = [
  { value: "PHONE", labelKey: "orderSourcePhone" },
  { value: "FACEBOOK", labelKey: "orderSourceFacebook" },
  { value: "WHATSAPP", labelKey: "orderSourceWhatsapp" },
  { value: "WEB", labelKey: "orderSourceWeb" },
  { value: "WEB_STORE", labelKey: "orderSourceWebStore" },
  { value: "DARAZ", labelKey: "orderSourceDaraz" },
  { value: "FOODPANDA", labelKey: "orderSourceFoodpanda" },
];

export const COURIER_OPTIONS = [
  "Pathao",
  "RedX",
  "Steadfast",
  "eCourier",
  "Paperfly",
  "Store delivery",
];
