const path = require("path");

// Load .env from backend root regardless of where the process was started.
require("dotenv").config({ path: path.resolve(__dirname, "../../.env") });

const isProd = (process.env.NODE_ENV || "development") === "production";

function readString(key, { required = false, defaultValue } = {}) {
  const raw = process.env[key];
  if (raw === undefined || raw === "") {
    if (required) {
      throw new Error(
        `[config] Missing required env var ${key}. Copy backend/.env.example to backend/.env and fill it in.`
      );
    }
    return defaultValue;
  }
  return String(raw);
}

function readInt(key, { required = false, defaultValue } = {}) {
  const raw = readString(key, { required, defaultValue: defaultValue?.toString() });
  if (raw === undefined) return undefined;
  const n = Number.parseInt(raw, 10);
  if (!Number.isFinite(n)) {
    throw new Error(`[config] Env var ${key} must be an integer (got "${raw}").`);
  }
  return n;
}

function readList(key, { defaultValue = [] } = {}) {
  const raw = process.env[key];
  if (!raw) return defaultValue;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

const jwtSecret = readString("JWT_SECRET", { required: isProd, defaultValue: "dev_secret_do_not_use_in_prod" });
if (jwtSecret === "dev_secret_do_not_use_in_prod" && isProd) {
  throw new Error("[config] JWT_SECRET must be set to a strong random value in production.");
}
if (jwtSecret.length < 24 && isProd) {
  throw new Error("[config] JWT_SECRET must be at least 24 characters in production.");
}

const databaseUrl = readString("DATABASE_URL", { required: true });

const allowedOrigins = readList("ALLOWED_ORIGINS", {
  defaultValue: isProd ? [] : ["http://localhost:5173", "http://127.0.0.1:5173"],
});

// Fail fast in production on weak/default operational secrets. These are read
// via process.env at their call sites; we only validate here so a misconfigured
// deployment refuses to boot instead of silently using guessable values.
if (isProd) {
  const managerPin = process.env.MANAGER_APPROVAL_PIN;
  if (!managerPin || managerPin.trim() === "" || managerPin.trim() === "1234") {
    throw new Error(
      "[config] MANAGER_APPROVAL_PIN must be set to a strong, non-default value in production (the default \"1234\" is not allowed)."
    );
  }
  const otpSalt = process.env.LOYALTY_OTP_SALT;
  if (!otpSalt || otpSalt.trim().length < 16) {
    throw new Error(
      "[config] LOYALTY_OTP_SALT must be set to a random value of at least 16 characters in production."
    );
  }
}

const config = Object.freeze({
  env: process.env.NODE_ENV || "development",
  isProd,
  port: readInt("PORT", { defaultValue: 5001 }),
  jwtSecret,
  jwtExpiresIn: readString("JWT_EXPIRES_IN", { defaultValue: "24h" }),
  databaseUrl,
  allowedOrigins,
  trustProxy: readString("TRUST_PROXY", { defaultValue: "loopback" }),
  rateLimit: {
    loginWindowMs: readInt("RATE_LIMIT_LOGIN_WINDOW_MS", { defaultValue: 15 * 60 * 1000 }),
    loginMax: readInt("RATE_LIMIT_LOGIN_MAX", { defaultValue: 10 }),
    bootstrapWindowMs: readInt("RATE_LIMIT_BOOTSTRAP_WINDOW_MS", { defaultValue: 60 * 60 * 1000 }),
    bootstrapMax: readInt("RATE_LIMIT_BOOTSTRAP_MAX", { defaultValue: 5 }),
    // Generous global ceiling per IP — high enough not to disrupt a busy
    // multi-terminal store behind one NAT, low enough to blunt scraping/DoS.
    apiWindowMs: readInt("RATE_LIMIT_API_WINDOW_MS", { defaultValue: 15 * 60 * 1000 }),
    apiMax: readInt("RATE_LIMIT_API_MAX", { defaultValue: 5000 }),
    // Strict ceiling for public OTP requests (SMS cost / OTP-bombing abuse).
    otpWindowMs: readInt("RATE_LIMIT_OTP_WINDOW_MS", { defaultValue: 15 * 60 * 1000 }),
    otpMax: readInt("RATE_LIMIT_OTP_MAX", { defaultValue: 20 }),
  },
  security: {
    // Optional shared secret for verifying provider payment callbacks. When set,
    // the MFS callback endpoint requires a matching x-callback-secret header or
    // ?secret= query param. Leave unset to accept callbacks (still re-verified
    // against the provider before a session is marked paid).
    mfsCallbackSecret: readString("MFS_CALLBACK_SECRET", { required: false }),
  },
  bootstrap: {
    // Optional shared secret required to call /api/bootstrap/seed.
    // If unset in dev, seed is open; if unset in prod, seed is blocked entirely.
    seedToken: readString("BOOTSTRAP_SEED_TOKEN", { required: false }),
  },
  reportStore: {
    name: readString("REPORT_STORE_NAME", { defaultValue: "BD Smart POS" }),
    address: readString("REPORT_STORE_ADDRESS", { defaultValue: "Dhaka, Bangladesh" }),
    phone: readString("REPORT_STORE_PHONE", { defaultValue: "" }),
    footer: readString("REPORT_FOOTER_TEXT", { defaultValue: "Generated by BD Smart POS" }),
  },
});

module.exports = config;
