SET @db := DATABASE();

SET @sql := (
  SELECT IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Purchase' AND COLUMN_NAME = 'transportationCost') > 0,
    'SELECT 1',
    'ALTER TABLE `Purchase` ADD COLUMN `transportationCost` DOUBLE NOT NULL DEFAULT 0'
  )
);
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := (
  SELECT IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Purchase' AND COLUMN_NAME = 'bribesCost') > 0,
    'SELECT 1',
    'ALTER TABLE `Purchase` ADD COLUMN `bribesCost` DOUBLE NOT NULL DEFAULT 0'
  )
);
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql := (
  SELECT IF(
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'Purchase' AND COLUMN_NAME = 'extraOtherCost') > 0,
    'SELECT 1',
    'ALTER TABLE `Purchase` ADD COLUMN `extraOtherCost` DOUBLE NOT NULL DEFAULT 0'
  )
);
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
