SET @db := DATABASE();
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'WebhookDeliveryLog' AND COLUMN_NAME = 'requestBody') > 0, 'SELECT 1', 'ALTER TABLE `WebhookDeliveryLog` ADD COLUMN `requestBody` MEDIUMTEXT NULL'));
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
