/** Product master form defaults and mapping helpers. */

export const UOM_OPTIONS = ["PCS", "KG", "GM", "LTR", "ML", "BOX", "STRIP", "BOTTLE", "PACK", "PAIR", "SET"];

export const STORAGE_OPTIONS = [
  { value: "", labelKey: "prodStorageNone" },
  { value: "ROOM", labelKey: "prodStorageRoom" },
  { value: "COOL", labelKey: "prodStorageCool" },
  { value: "COLD", labelKey: "prodStorageCold" },
  { value: "FREEZER", labelKey: "prodStorageFreezer" },
  { value: "DRY", labelKey: "prodStorageDry" },
];

export const CONDITION_OPTIONS = [
  { value: "", labelKey: "prodConditionUnset" },
  { value: "NEW", labelKey: "prodConditionNew" },
  { value: "REFURBISHED", labelKey: "prodConditionRefurbished" },
  { value: "USED", labelKey: "prodConditionUsed" },
];

export const PRODUCT_FORM_SECTIONS = [
  { id: "identity", labelKey: "prodSectionIdentity" },
  { id: "pricing", labelKey: "prodSectionPricing" },
  { id: "inventory", labelKey: "prodSectionInventory" },
  { id: "compliance", labelKey: "prodSectionCompliance" },
  { id: "pharmacy", labelKey: "prodSectionPharmacy" },
  { id: "attributes", labelKey: "prodSectionAttributes" },
  { id: "media", labelKey: "prodSectionMedia" },
  { id: "notes", labelKey: "prodSectionNotes" },
];

export const EMPTY_PRODUCT_FORM = {
  name: "",
  nameBn: "",
  description: "",
  shortDescription: "",
  category: "",
  categoryId: "",
  sku: "",
  barcode: "",
  brand: "",
  model: "",
  manufacturer: "",
  countryOfOrigin: "",
  unitOfMeasure: "PCS",
  saleUnit: "PCS",
  tagsText: "",
  isActive: true,
  unitPrice: "",
  price: "",
  mrp: "",
  hsCode: "",
  vatRate: "",
  reorderLevel: "",
  defaultDiscountType: "",
  defaultDiscountValue: "",
  stock: "",
  batchTracked: false,
  trackExpiry: false,
  trackSerial: false,
  trackImei: false,
  requiresKyc: false,
  warrantyDays: "",
  isRawMaterial: false,
  isManufactured: false,
  sellByWeight: false,
  stockKg: "",
  hasVariants: false,
  weightGrams: "",
  shelfLifeDays: "",
  storageCondition: "",
  genericName: "",
  strength: "",
  dosageForm: "",
  drugRegNo: "",
  size: "",
  color: "",
  specification: "",
  imageUrl: "",
  imageGalleryText: "",
  internalNotes: "",
  sdRate: "",
  nbrProductCode: "",
  bstiCertNo: "",
  isHalalCertified: false,
  halalCertNo: "",
  importerName: "",
  importerAddress: "",
  productCondition: "",
  purchaseUnit: "",
  unitsPerPack: "",
  packsPerCarton: "",
  netWeightGrams: "",
  grossWeightGrams: "",
  lengthCm: "",
  widthCm: "",
  heightCm: "",
  minOrderQty: "",
  maxOrderQty: "",
  leadTimeDays: "",
};

export function tagsToText(tags) {
  if (!Array.isArray(tags)) return "";
  return tags.map((x) => String(x || "").trim()).filter(Boolean).join(", ");
}

export function textToTags(text) {
  return String(text || "")
    .split(/[,\n]/)
    .map((x) => x.trim())
    .filter(Boolean)
    .slice(0, 30);
}

export function rowToProductForm(row) {
  if (!row) return { ...EMPTY_PRODUCT_FORM };
  return {
    name: row.name || "",
    nameBn: row.nameBn || "",
    description: row.description || "",
    shortDescription: row.shortDescription || "",
    category: row.category || "",
    categoryId: row.categoryId != null ? String(row.categoryId) : "",
    sku: row.sku || "",
    barcode: row.barcode || "",
    brand: row.brand || "",
    model: row.model || "",
    manufacturer: row.manufacturer || "",
    countryOfOrigin: row.countryOfOrigin || "",
    unitOfMeasure: row.saleUnit || row.unitOfMeasure || "PCS",
    saleUnit: row.saleUnit || row.unitOfMeasure || "PCS",
    tagsText: tagsToText(row.tags),
    isActive: row.isActive !== false,
    unitPrice: row.unitPrice ?? "",
    price: row.price ?? "",
    mrp: row.mrp ?? "",
    hsCode: row.hsCode || "",
    vatRate: row.vatRate ?? "",
    reorderLevel: row.reorderLevel ?? "",
    defaultDiscountType: row.defaultDiscountType || "",
    defaultDiscountValue: row.defaultDiscountValue ?? "",
    stock: row.stock ?? "",
    batchTracked: Boolean(row.batchTracked),
    trackExpiry: Boolean(row.trackExpiry),
    trackSerial: Boolean(row.trackSerial),
    trackImei: Boolean(row.trackImei),
    requiresKyc: Boolean(row.requiresKyc),
    warrantyDays: row.warrantyDays ?? "",
    isRawMaterial: Boolean(row.isRawMaterial),
    isManufactured: Boolean(row.isManufactured),
    sellByWeight: Boolean(row.sellByWeight),
    stockKg: row.stockKg ?? "",
    hasVariants: Boolean(row.hasVariants),
    weightGrams: row.weightGrams ?? "",
    shelfLifeDays: row.shelfLifeDays ?? "",
    storageCondition: row.storageCondition || "",
    genericName: row.genericName || "",
    strength: row.strength || "",
    dosageForm: row.dosageForm || "",
    drugRegNo: row.drugRegNo || "",
    size: row.size || "",
    color: row.color || "",
    specification: row.specification || "",
    imageUrl: row.imageUrl || "",
    imageGalleryText: Array.isArray(row.imageGallery) ? row.imageGallery.join("\n") : "",
    internalNotes: row.internalNotes || "",
    sdRate: row.sdRate ?? "",
    nbrProductCode: row.nbrProductCode || "",
    bstiCertNo: row.bstiCertNo || "",
    isHalalCertified: Boolean(row.isHalalCertified),
    halalCertNo: row.halalCertNo || "",
    importerName: row.importerName || "",
    importerAddress: row.importerAddress || "",
    productCondition: row.productCondition || "",
    purchaseUnit: row.purchaseUnit || "",
    unitsPerPack: row.unitsPerPack ?? "",
    packsPerCarton: row.packsPerCarton ?? "",
    netWeightGrams: row.netWeightGrams ?? "",
    grossWeightGrams: row.grossWeightGrams ?? "",
    lengthCm: row.lengthCm ?? "",
    widthCm: row.widthCm ?? "",
    heightCm: row.heightCm ?? "",
    minOrderQty: row.minOrderQty ?? "",
    maxOrderQty: row.maxOrderQty ?? "",
    leadTimeDays: row.leadTimeDays ?? "",
  };
}

export function productFormToPayload(form, attributeDraft) {
  const imageGallery = String(form.imageGalleryText || "")
    .split(/[\n,]/)
    .map((x) => x.trim())
    .filter(Boolean)
    .slice(0, 20);

  return {
    name: form.name,
    nameBn: form.nameBn || null,
    description: form.description || null,
    shortDescription: form.shortDescription || null,
    category: form.category || null,
    categoryId: form.categoryId ? Number(form.categoryId) : null,
    sku: form.sku || null,
    barcode: form.barcode || null,
    brand: form.brand || null,
    model: form.model || null,
    manufacturer: form.manufacturer || null,
    countryOfOrigin: form.countryOfOrigin || null,
    saleUnit: form.saleUnit || form.unitOfMeasure || "PCS",
    unitOfMeasure: form.saleUnit || form.unitOfMeasure || "PCS",
    tags: textToTags(form.tagsText),
    isActive: Boolean(form.isActive),
    unitPrice: Number(form.unitPrice || 0),
    price: Number(form.price),
    mrp: Number(form.mrp || 0),
    hsCode: form.hsCode || null,
    stock: Number(form.stock),
    size: form.size || null,
    color: form.color || null,
    specification: form.specification || null,
    attributeValues: attributeDraft || {},
    imageUrl: form.imageUrl || null,
    imageGallery,
    vatRate: Number(form.vatRate || 0),
    reorderLevel: Number(form.reorderLevel || 0),
    defaultDiscountType: form.defaultDiscountType || null,
    defaultDiscountValue: Number(form.defaultDiscountValue || 0),
    batchTracked: Boolean(form.batchTracked),
    trackExpiry: Boolean(form.trackExpiry),
    trackSerial: Boolean(form.trackSerial),
    trackImei: Boolean(form.trackImei),
    requiresKyc: Boolean(form.requiresKyc),
    warrantyDays: form.warrantyDays !== "" && form.warrantyDays != null ? Number(form.warrantyDays) : null,
    isRawMaterial: Boolean(form.isRawMaterial),
    isManufactured: Boolean(form.isManufactured),
    sellByWeight: Boolean(form.sellByWeight),
    stockKg: Number(form.stockKg || 0),
    hasVariants: Boolean(form.hasVariants),
    weightGrams: form.weightGrams !== "" ? Number(form.weightGrams) : null,
    shelfLifeDays: form.shelfLifeDays !== "" ? Number(form.shelfLifeDays) : null,
    storageCondition: form.storageCondition || null,
    genericName: form.genericName || null,
    strength: form.strength || null,
    dosageForm: form.dosageForm || null,
    drugRegNo: form.drugRegNo || null,
    internalNotes: form.internalNotes || null,
    sdRate: Number(form.sdRate || 0),
    nbrProductCode: form.nbrProductCode || null,
    bstiCertNo: form.bstiCertNo || null,
    isHalalCertified: Boolean(form.isHalalCertified),
    halalCertNo: form.halalCertNo || null,
    importerName: form.importerName || null,
    importerAddress: form.importerAddress || null,
    productCondition: form.productCondition || null,
    purchaseUnit: form.purchaseUnit || null,
    unitsPerPack: form.unitsPerPack !== "" && form.unitsPerPack != null ? Number(form.unitsPerPack) : null,
    packsPerCarton: form.packsPerCarton !== "" && form.packsPerCarton != null ? Number(form.packsPerCarton) : null,
    netWeightGrams: form.netWeightGrams !== "" && form.netWeightGrams != null ? Number(form.netWeightGrams) : null,
    grossWeightGrams: form.grossWeightGrams !== "" && form.grossWeightGrams != null ? Number(form.grossWeightGrams) : null,
    lengthCm: form.lengthCm !== "" && form.lengthCm != null ? Number(form.lengthCm) : null,
    widthCm: form.widthCm !== "" && form.widthCm != null ? Number(form.widthCm) : null,
    heightCm: form.heightCm !== "" && form.heightCm != null ? Number(form.heightCm) : null,
    minOrderQty: form.minOrderQty !== "" && form.minOrderQty != null ? Number(form.minOrderQty) : null,
    maxOrderQty: form.maxOrderQty !== "" && form.maxOrderQty != null ? Number(form.maxOrderQty) : null,
    leadTimeDays: form.leadTimeDays !== "" && form.leadTimeDays != null ? Number(form.leadTimeDays) : null,
  };
}
